train_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\train.ocr"
train_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\train.std"
eval_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\dev.ocr"
eval_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\dev.std"
test_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\test.ocr"
test_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\test.std"
vocabs_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\source_vocab"
vocabs_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\target_vocab"
model_dir: "E:\\LTTProject\\data\\model"
vocab_size: 3537
embedding_size: 64
num_units: 32
input_keep_prob: 1.0
encode_layzer_size: 4
buffer_size: 1000
repeat: 2
reshuffle_each_iteration: true
batch_size: 10
random_seed: 1000
save_summary_steps: 1000
keep_checkpoint_max: 5
log_step_count_steps: 500
max_steps: 5000
eval_steps: 100