train_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\train.ocr"
train_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\train.std"
eval_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\dev.ocr"
eval_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\dev.std"
test_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\test.ocr"
test_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\test.std"
vocabs_features_file: "E:\\LTTProject\\SEQ2SEQ\\data\\source_vocab"
vocabs_labels_file: "E:\\LTTProject\\SEQ2SEQ\\data\\target_vocab"
model_dir: "E:\\LTTProject\\SEQ2SEQ\\data\\model"
num_parallel_calls: 4
embedding_size: 512
num_units: 32
reshuffle_each_iteration: true
input_keep_prob: 0.7
encode_layzer_size: 4
buffer_size: 1000
repeat: -1
batch_size: 32
random_seed: 4000
save_summary_steps: 1000
keep_checkpoint_max: 5
log_step_count_steps: 1000
max_steps: 2000
eval_steps: 100
vocab_size: 3603
src_max_len: 50
tgt_max_len: 50