train_features_file: "/home/liutingting/data/train.ocr"
train_labels_file: "/home/liutingting/data/train.std"
eval_features_file: "/home/liutingting/data/dev.ocr"
eval_labels_file: "/home/liutingting/data/dev.std"
test_features_file: "/home/liutingting/data/test.ocr"
test_labels_file: "/home/liutingting/data/test.std"
vocabs_features_file: "/home/liutingting/data/source_vocab"
vocabs_labels_file: "/home/liutingting/data/target_vocab"
model_dir: "/home/liutingting/data/model"
num_parallel_calls: 4
embedding_size: 32
num_units: 32
reshuffle_each_iteration: true
input_keep_prob: 0.7
encode_layzer_size: 4
buffer_size: 10000
repeat: 1
batch_size: 16
random_seed: 400000
save_summary_steps: 2000
keep_checkpoint_max: 5
log_step_count_steps: 2000
max_steps: 400000
eval_steps: 100
vocab_size: 7744
src_max_len: 50
tgt_max_len: 50